### ISSUE TITLE
Type Error - Fix Bug where postcode not in postcodes.csv causes a crash

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#34]
`Currently there is a bug that causes the postcode crime checker to crash. This needs to be remedied before release.`

I suspect that this is when we have an invalid postcode entered. Will investigate and then find solution. - CONFIRMED

Plan:
 - [ ] Create logic to confirm that the user's postcode is in the list.

Simplest method is likely to be to have an initial program get all of the postcodes which are in the postcodes.csv file (that start with "EX"?) and to ensure that the user only inputs a postcode that is in that list by rejecting anything that is not.

Solution steps:
 - [x] Create the program that will extract the valid postcodes
 - [ ] Have this run in main.py before load menu
 - [x] Have a getter method in the new module such that it will allow UI.py access to that list
 - [x] Create logic that confirms if a user's postcode is in that list
 - [x] Generate the correct error message if it is not in the list. 
 - [x] Do not allow the program to fail!

Printout of the errors we are getting:
```Traceback (most recent call last):
  File ".\main.py", line 17, in <module>
    run()
  File ".\main.py", line 14, in run
    UI.load_menu()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 53, in load_menu
    select_postcode()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 114, in select_postcode
    load_menu()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 55, in load_menu
    select_radius()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 152, in select_radius
    load_menu()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 57, in load_menu
    select_sort_data()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 197, in select_sort_data
    load_menu()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 59, in load_menu
    select_file_name()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 223, in select_file_name
    load_menu()
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 61, in load_menu
    confirm_data(bcorrect_data)
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\UI.py", line 301, in confirm_data
    generate_report.generate_report(arguments_dict)
  File "C:\Users\SamReece\Documents\GitHub\PostcodeCrimeChecker\generate_report.py", line 31, in generate_report
    sorted_data = data_sorter.data_sorter(postcode_centre[latitude_pos], postcode_centre[longitude_pos], arguments_dictionary['radius'], all_crime_records, arguments_dictionary['data_sort'])
TypeError: 'type' object is not subscriptable

**Comment by FebruaryRain** [comment]
Done, extract_valid_postcodes module; implemented and tested (docstrings to be done in next 5 minutes).
